[package]
name = "tp-example"
version = "0.1.0"
authors = ["Cris Hall-Ramos <crishallramos@yahoo.com>"]

[lib]
name = "rust"
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true

[dependencies]
gcn = { git = "https://github.com/CryZe/gcn", rev = "00cacaad3e3eb2ed2bd54a4a1ab6c3a469a8b96f" }
gcn-fonts = { git = "https://github.com/CryZe/gcn-fonts", rev = "05fdb050023281ab9e77d9838b3d71c682723f1c" }
