[info]
game-name = "TP:GZ"
full-game-name = "The Legend of Zelda: Twilight Princess Debug"
developer-name = "Twilight Princess Community"
full-developer-name = "Speedrun Community"

[src]
iso = "gz2e01.iso"
link = ["target/powerpc-unknown-linux-gnu/release/librust.a"]
patch = "src/patch.asm"
map = "map/Final/Release/frameworkF.map"

[build]
map = "target/framework.map"
iso = "target/tpgz.iso"

[link]
entries = ["draw", "game_loop", "read_controller"]
base = "0x8046_0000"
