[info]
game-name = "TP:GZ"
full-game-name = "The Legend of Zelda: Twilight Princess Debug"
developer-name = "Twilight Princess Community"
full-developer-name = "Speedrun Community"

[src]
iso = "gz2e01.iso"
patch = "src/patch.asm"
map = "map/Final/Release/frameworkF.map"

[build]
map = "target/GZ2E01.map"
iso = "target/tpgz.iso"

[link]
entries = ["draw", "game_loop", "read_controller", "init_once"]
base = "0x8046_0000"
