[info]
game-name = "Twilight Princess Example"
full-game-name = "The Legend of Zelda: Twilight Princess"
developer-name = "MidKnight"
full-developer-name = "Speedrun Community"

[src]
iso = "gz2e01.iso"
link = ["target/powerpc-unknown-linux-gnu/release/librust.a"]
patch = "src/patch.asm"
map = "map/Final/Release/frameworkF.map"

[build]
map = "target/framework.map"
iso = "target/rom_hack.iso"

[link]
entries = ["draw"]
base = "0x8046_0000"
